server:
  port: 8080
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jwt:
  secret: hidfshndfs
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://123.57.221.79:3306/table_tennis_system?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: Lcp20010801..
      driver-class-name: com.mysql.cj.jdbc.Driver
      druid:
        initial-size: 5
        min-idle: 5
        max-active: 20
        max-wait: 60000 # ??
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000 # ??
        min-evictable-idle-time-millis: 1800000 # ??
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB